/**
 * Critical flow E2E tests
 *
 * Tests the full manager → staff lifecycle:
 *   login → create staff → assign task → (staff completes task) → verify KPI updates
 *
 * Prerequisites (set via env vars or .env.test):
 *   WEB_URL          - Web dashboard URL  (default: http://localhost:3000)
 *   MANAGER_PHONE    - Manager phone used for login
 *   MANAGER_PASSWORD - Manager password
 *   BACKEND_URL      - Backend API URL    (default: http://localhost:8080)
 *
 * Run:
 *   npm test
 *   WEB_URL=http://staging.example.com npm test
 */

import { test, expect, Page, request } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { EmployeesPage } from '../pages/EmployeesPage';
import { TasksPage } from '../pages/TasksPage';
import { KpiPage } from '../pages/KpiPage';

const MANAGER_PHONE    = process.env.MANAGER_PHONE    ?? '0000000001';
const MANAGER_PASSWORD = process.env.MANAGER_PASSWORD ?? 'TestPass123!';
const BACKEND_URL      = process.env.BACKEND_URL      ?? 'http://localhost:8080';

// Unique per-run suffix prevents collisions in parallel CI environments
const RUN_ID = Date.now().toString().slice(-6);
const STAFF_PHONE   = `999${RUN_ID}`;
const STAFF_NAME    = `E2E Staff ${RUN_ID}`;
const STAFF_PASS    = 'StaffPass123!';
const TASK_TITLE    = `E2E Task ${RUN_ID}`;

// ---- SUITE 1: Authentication ----

test.describe('Authentication', () => {
  test('unauthenticated user is redirected to /login', async ({ page }) => {
    await page.goto('/dashboard');
    await expect(page).toHaveURL(/\/login/, { timeout: 8_000 });
  });

  test('manager can log in and reach dashboard', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.loginAsManager(MANAGER_PHONE, MANAGER_PASSWORD);
    await expect(page).toHaveURL(/\/dashboard/);
  });

  test('invalid credentials shows error', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await page.getByLabel(/phone/i).fill('0000000000');
    await page.getByLabel(/password/i).fill('wrongpass');
    await page.getByRole('button', { name: /sign in|login/i }).click();
    await expect(page.getByText(/invalid|error|incorrect/i)).toBeVisible({ timeout: 8_000 });
  });
});

// ---- SUITE 2: Staff Management ----

test.describe('Staff management', () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.loginAsManager(MANAGER_PHONE, MANAGER_PASSWORD);
  });

  test.afterAll(() => page.close());

  test('manager can create a new staff member', async () => {
    const employeesPage = new EmployeesPage(page);
    await employeesPage.goto();
    await employeesPage.createStaff({
      phone: STAFF_PHONE,
      displayName: STAFF_NAME,
      password: STAFF_PASS,
    });
    await employeesPage.goto();   // refresh list
    await employeesPage.staffExists(STAFF_NAME);
  });

  test('employees page shows paginated list', async () => {
    const employeesPage = new EmployeesPage(page);
    await employeesPage.goto();
    // Page should render without error (list or empty state)
    await expect(page.locator('main, [data-testid="employees-container"]')).toBeVisible();
  });
});

// ---- SUITE 3: Task Assignment ----

test.describe('Task assignment', () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.loginAsManager(MANAGER_PHONE, MANAGER_PASSWORD);
  });

  test.afterAll(() => page.close());

  test('manager can assign a task to new staff', async () => {
    const tasksPage = new TasksPage(page);
    await tasksPage.goto();
    await tasksPage.createTask({
      title: TASK_TITLE,
      description: 'Auto-generated by E2E test suite.',
      assigneeName: STAFF_NAME,
      priority: 'HIGH',
      deadlineDaysFromNow: 7,
    });
    await tasksPage.goto();
    await tasksPage.taskExists(TASK_TITLE);
  });

  test('tasks list renders with pagination controls', async () => {
    await page.goto('/dashboard/tasks');
    await page.waitForLoadState('networkidle');
    // Should show tasks or empty state — no uncaught error
    await expect(page.locator('body')).not.toContainText('500');
    await expect(page.locator('body')).not.toContainText('Error');
  });
});

// ---- SUITE 4: Task Completion via API (staff role) ----

test.describe('Task completion and KPI update', () => {
  /**
   * Staff-side completion is done via API call (we simulate the mobile app).
   * We then verify that the KPI dashboard reflects the change as manager.
   */

  test('staff completing a task triggers KPI update (API-level)', async () => {
    // 1. Authenticate as staff
    const apiCtx = await request.newContext({ baseURL: BACKEND_URL });

    const authResp = await apiCtx.post('/api/auth/verify', {
      data: { phone: STAFF_PHONE, password: STAFF_PASS },
    });

    if (!authResp.ok()) {
      // Staff login may fail if running against a fresh env without real Firebase.
      // Skip instead of failing the suite.
      test.skip(true, 'Staff account not available in this env — skipping completion test');
    }

    const { data: { token, uid } } = await authResp.json();

    // 2. Get staff's tasks
    const tasksResp = await apiCtx.get('/api/tasks', {
      headers: { Authorization: `Bearer ${token}` },
    });
    expect(tasksResp.ok()).toBeTruthy();

    const tasksBody = await tasksResp.json();
    const tasks: Array<{ id: string; title: string; status: string }> =
        tasksBody.data?.content ?? tasksBody.data ?? [];

    const target = tasks.find(t => t.title === TASK_TITLE && t.status === 'PENDING');
    if (!target) {
      test.skip(true, `Task "${TASK_TITLE}" not found or already completed`);
    }

    // 3. Complete the task
    const completeResp = await apiCtx.put(`/api/tasks/${target!.id}/complete`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    expect(completeResp.ok()).toBeTruthy();

    const completed = await completeResp.json();
    expect(completed.data.status).toBe('COMPLETED');

    await apiCtx.dispose();
  });

  test('KPI dashboard shows staff after task completion', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.loginAsManager(MANAGER_PHONE, MANAGER_PASSWORD);

    const kpiPage = new KpiPage(page);
    await kpiPage.goto();

    // Staff should appear in rankings once KPI is calculated
    await kpiPage.staffAppearsInRankings(STAFF_NAME);
  });
});

// ---- SUITE 5: Validation error handling ----

test.describe('Form validation', () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.loginAsManager(MANAGER_PHONE, MANAGER_PASSWORD);
  });

  test.afterAll(() => page.close());

  test('creating task with empty title shows validation error', async () => {
    await page.goto('/dashboard/tasks');
    await page.waitForLoadState('networkidle');

    await page.getByRole('button', { name: /add task|new task|create task/i }).click();
    const dialog = page.getByRole('dialog');
    // Submit without filling required fields
    await dialog.getByRole('button', { name: /create|save|submit/i }).click();

    // Expect inline validation message (from react-hook-form) or API error toast
    await expect(
      page.getByText(/required|title is required|please fill/i)
    ).toBeVisible({ timeout: 5_000 });
  });
});
